/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class casual_service_name_mapping {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected casual_service_name_mapping(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(casual_service_name_mapping obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xatmi_serverJNI.delete_casual_service_name_mapping(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFunctionPointer(SWIGTYPE_p_tpservice value) {
    xatmi_serverJNI.casual_service_name_mapping_functionPointer_set(swigCPtr, this, SWIGTYPE_p_tpservice.getCPtr(value));
  }

  public SWIGTYPE_p_tpservice getFunctionPointer() {
    return new SWIGTYPE_p_tpservice(xatmi_serverJNI.casual_service_name_mapping_functionPointer_get(swigCPtr, this), true);
  }

  public void setName(String value) {
    xatmi_serverJNI.casual_service_name_mapping_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return xatmi_serverJNI.casual_service_name_mapping_name_get(swigCPtr, this);
  }

  public void setType(SWIGTYPE_p_uint64_t value) {
    xatmi_serverJNI.casual_service_name_mapping_type_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getType() {
    return new SWIGTYPE_p_uint64_t(xatmi_serverJNI.casual_service_name_mapping_type_get(swigCPtr, this), true);
  }

  public void setTransaction(SWIGTYPE_p_uint64_t value) {
    xatmi_serverJNI.casual_service_name_mapping_transaction_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getTransaction() {
    return new SWIGTYPE_p_uint64_t(xatmi_serverJNI.casual_service_name_mapping_transaction_get(swigCPtr, this), true);
  }

  public casual_service_name_mapping() {
    this(xatmi_serverJNI.new_casual_service_name_mapping(), true);
  }

}
