/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../../../xatmi/include/xa.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_xaJNI_XIDDATASIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(128);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xid_1t_1formatID_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->formatID = arg2;
}


SWIGEXPORT jint JNICALL Java_xaJNI_xid_1t_1formatID_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  result = (long) ((arg1)->formatID);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xid_1t_1gtrid_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->gtrid_length = arg2;
}


SWIGEXPORT jint JNICALL Java_xaJNI_xid_1t_1gtrid_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  result = (long) ((arg1)->gtrid_length);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xid_1t_1bqual_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->bqual_length = arg2;
}


SWIGEXPORT jint JNICALL Java_xaJNI_xid_1t_1bqual_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  result = (long) ((arg1)->bqual_length);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xid_1t_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  char *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->data, (const char *)arg2, 128-1);
      arg1->data[128-1] = 0;
    } else {
      arg1->data[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_xaJNI_xid_1t_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xid_t **)&jarg1; 
  result = (char *)(char *) ((arg1)->data);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_new_1xid_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct xid_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct xid_t *)calloc(1, sizeof(struct xid_t));
  *(struct xid_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_delete_1xid_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct xid_t *arg1 = (struct xid_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct xid_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_xaJNI_ax_1reg(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_, jint jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  XID *arg2 = (XID *) 0 ;
  long arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (int)jarg1; 
  arg2 = *(XID **)&jarg2; 
  arg3 = (long)jarg3; 
  result = (int)ax_reg(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_ax_1unreg(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  long arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (long)jarg2; 
  result = (int)ax_unreg(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_RMNAMESZ_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(32);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  char *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->name, (const char *)arg2, 32-1);
      arg1->name[32-1] = 0;
    } else {
      arg1->name[0] = 0;
    }
  }
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_xaJNI_xa_1switch_1t_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (char *)(char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1flags_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->flags = arg2;
}


SWIGEXPORT jint JNICALL Java_xaJNI_xa_1switch_1t_1flags_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (long) ((arg1)->flags);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1version_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->version = arg2;
}


SWIGEXPORT jint JNICALL Java_xaJNI_xa_1switch_1t_1version_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (long) ((arg1)->version);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1open_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(char const *,int,long) = (int (*)(char const *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(char const *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_open_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1open_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(char const *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(char const *,int,long)) ((arg1)->xa_open_entry);
  *(int (**)(char const *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1close_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(char const *,int,long) = (int (*)(char const *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(char const *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_close_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1close_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(char const *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(char const *,int,long)) ((arg1)->xa_close_entry);
  *(int (**)(char const *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1start_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(XID *,int,long) = (int (*)(XID *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(XID *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_start_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1start_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(XID *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(XID *,int,long)) ((arg1)->xa_start_entry);
  *(int (**)(XID *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1end_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(XID *,int,long) = (int (*)(XID *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(XID *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_end_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1end_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(XID *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(XID *,int,long)) ((arg1)->xa_end_entry);
  *(int (**)(XID *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1rollback_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(XID *,int,long) = (int (*)(XID *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(XID *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_rollback_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1rollback_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(XID *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(XID *,int,long)) ((arg1)->xa_rollback_entry);
  *(int (**)(XID *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1prepare_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(XID *,int,long) = (int (*)(XID *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(XID *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_prepare_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1prepare_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(XID *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(XID *,int,long)) ((arg1)->xa_prepare_entry);
  *(int (**)(XID *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1commit_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(XID *,int,long) = (int (*)(XID *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(XID *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_commit_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1commit_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(XID *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(XID *,int,long)) ((arg1)->xa_commit_entry);
  *(int (**)(XID *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1recover_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(XID *,long,int,long) = (int (*)(XID *,long,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(XID *,long,int,long))&jarg2; 
  if (arg1) (arg1)->xa_recover_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1recover_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(XID *,long,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(XID *,long,int,long)) ((arg1)->xa_recover_entry);
  *(int (**)(XID *,long,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1forget_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(XID *,int,long) = (int (*)(XID *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(XID *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_forget_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1forget_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(XID *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(XID *,int,long)) ((arg1)->xa_forget_entry);
  *(int (**)(XID *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_xa_1switch_1t_1xa_1complete_1entry_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*arg2)(int *,int *,int,long) = (int (*)(int *,int *,int,long)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  arg2 = *(int (**)(int *,int *,int,long))&jarg2; 
  if (arg1) (arg1)->xa_complete_entry = arg2;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_xa_1switch_1t_1xa_1complete_1entry_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  int (*result)(int *,int *,int,long) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  result = (int (*)(int *,int *,int,long)) ((arg1)->xa_complete_entry);
  *(int (**)(int *,int *,int,long))&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_xaJNI_new_1xa_1switch_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct xa_switch_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct xa_switch_t *)calloc(1, sizeof(struct xa_switch_t));
  *(struct xa_switch_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xaJNI_delete_1xa_1switch_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct xa_switch_t *arg1 = (struct xa_switch_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct xa_switch_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_xaJNI_MAXINFOSIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(256);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMNOFLAGS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMREGISTER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00000001L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMNOMIGRATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00000002L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMUSEASYNC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00000004L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMASYNC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x80000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMONEPHASE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x40000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMFAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x20000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMNOWAIT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x10000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMRESUME_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x08000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMSUCCESS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x04000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMSUSPEND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x02000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMSTARTRSCAN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x01000000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMENDRSCAN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00800000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMMULTIPLE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00400000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMJOIN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00200000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMMIGRATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)(0x00100000L);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TM_1JOIN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TM_1RESUME_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TM_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMER_1TMERR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMER_1INVAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_TMER_1PROTO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBBASE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBROLLBACK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBCOMMFAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBDEADLOCK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBINTEGRITY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBOTHER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBPROTO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBTIMEOUT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBTRANSIENT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RBEND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(100+7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1NOMIGRATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1HEURHAZ_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1HEURCOM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1HEURRB_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1HEURMIX_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RETRY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1RDONLY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XA_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1ASYNC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1RMERR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1NOTA_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1INVAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1PROTO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1RMFAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1DUPID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xaJNI_XAER_1OUTSIDE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-9);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

