/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../../../xatmi/include/xatmi_server.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1functionPointer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  tpservice arg2 ;
  tpservice *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  argp2 = *(tpservice **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null tpservice");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->functionPointer = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1functionPointer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  tpservice result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  result =  ((arg1)->functionPointer);
  {
    tpservice * resultptr = (tpservice *) malloc(sizeof(tpservice));
    memmove(resultptr, &result, sizeof(tpservice));
    *(tpservice **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->name = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  result = (char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  argp2 = *(uint64_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  result =  ((arg1)->type);
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1transaction_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  argp2 = *(uint64_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->transaction = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1service_1name_1mapping_1transaction_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  result =  ((arg1)->transaction);
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_new_1casual_1service_1name_1mapping(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct casual_service_name_mapping *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct casual_service_name_mapping *)calloc(1, sizeof(struct casual_service_name_mapping));
  *(struct casual_service_name_mapping **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_delete_1casual_1service_1name_1mapping(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct casual_service_name_mapping *arg1 = (struct casual_service_name_mapping *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct casual_service_name_mapping **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1xa_1switch_1mapping_1key_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct casual_xa_switch_mapping *arg1 = (struct casual_xa_switch_mapping *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_xa_switch_mapping **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->key = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->key, (const char *)arg2);
    } else {
      arg1->key = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_xatmi_1serverJNI_casual_1xa_1switch_1mapping_1key_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct casual_xa_switch_mapping *arg1 = (struct casual_xa_switch_mapping *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_xa_switch_mapping **)&jarg1; 
  result = (char *) ((arg1)->key);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1xa_1switch_1mapping_1xaSwitch_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct casual_xa_switch_mapping *arg1 = (struct casual_xa_switch_mapping *) 0 ;
  struct xa_switch_t *arg2 = (struct xa_switch_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_xa_switch_mapping **)&jarg1; 
  arg2 = *(struct xa_switch_t **)&jarg2; 
  if (arg1) (arg1)->xaSwitch = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1xa_1switch_1mapping_1xaSwitch_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_xa_switch_mapping *arg1 = (struct casual_xa_switch_mapping *) 0 ;
  struct xa_switch_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_xa_switch_mapping **)&jarg1; 
  result = (struct xa_switch_t *) ((arg1)->xaSwitch);
  *(struct xa_switch_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_new_1casual_1xa_1switch_1mapping(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct casual_xa_switch_mapping *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct casual_xa_switch_mapping *)calloc(1, sizeof(struct casual_xa_switch_mapping));
  *(struct casual_xa_switch_mapping **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_delete_1casual_1xa_1switch_1mapping(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct casual_xa_switch_mapping *arg1 = (struct casual_xa_switch_mapping *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct casual_xa_switch_mapping **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1services_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  struct casual_service_name_mapping *arg2 = (struct casual_service_name_mapping *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  arg2 = *(struct casual_service_name_mapping **)&jarg2; 
  if (arg1) (arg1)->services = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1services_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  struct casual_service_name_mapping *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  result = (struct casual_service_name_mapping *) ((arg1)->services);
  *(struct casual_service_name_mapping **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1serviceInit_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  tpsvrinit_type arg2 = (tpsvrinit_type) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  arg2 = *(tpsvrinit_type *)&jarg2; 
  if (arg1) (arg1)->serviceInit = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1serviceInit_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  tpsvrinit_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  result = (tpsvrinit_type) ((arg1)->serviceInit);
  *(tpsvrinit_type *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1serviceDone_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  tpsvrdone_type arg2 = (tpsvrdone_type) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  arg2 = *(tpsvrdone_type *)&jarg2; 
  if (arg1) (arg1)->serviceDone = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1serviceDone_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  tpsvrdone_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  result = (tpsvrdone_type) ((arg1)->serviceDone);
  *(tpsvrdone_type *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1argc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->argc = arg2;
}


SWIGEXPORT jint JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1argc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  result = (int) ((arg1)->argc);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1argv_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  char **arg2 = (char **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  if (arg1) (arg1)->argv = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1argv_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  result = (char **) ((arg1)->argv);
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1xaSwitches_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  struct casual_xa_switch_mapping *arg2 = (struct casual_xa_switch_mapping *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  arg2 = *(struct casual_xa_switch_mapping **)&jarg2; 
  if (arg1) (arg1)->xaSwitches = arg2;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_casual_1server_1argument_1xaSwitches_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  struct casual_xa_switch_mapping *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  result = (struct casual_xa_switch_mapping *) ((arg1)->xaSwitches);
  *(struct casual_xa_switch_mapping **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_xatmi_1serverJNI_new_1casual_1server_1argument(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct casual_server_argument *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct casual_server_argument *)calloc(1, sizeof(struct casual_server_argument));
  *(struct casual_server_argument **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_xatmi_1serverJNI_delete_1casual_1server_1argument(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_xatmi_1serverJNI_casual_1initialize_1server(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3, jobject jarg3_, jlong jarg4) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  struct casual_service_name_mapping *arg3 = (struct casual_service_name_mapping *) 0 ;
  size_t arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  arg3 = *(struct casual_service_name_mapping **)&jarg3; 
  arg4 = (size_t)jarg4; 
  result = (int)casual_initialize_server(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_xatmi_1serverJNI_casual_1start_1server(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct casual_server_argument *arg1 = (struct casual_server_argument *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct casual_server_argument **)&jarg1; 
  result = (int)casual_start_server(arg1);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

