/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class tpsvcinfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tpsvcinfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tpsvcinfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xatmiJNI.delete_tpsvcinfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    xatmiJNI.tpsvcinfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return xatmiJNI.tpsvcinfo_name_get(swigCPtr, this);
  }

  public void setData(String value) {
    xatmiJNI.tpsvcinfo_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return xatmiJNI.tpsvcinfo_data_get(swigCPtr, this);
  }

  public void setLen(int value) {
    xatmiJNI.tpsvcinfo_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return xatmiJNI.tpsvcinfo_len_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    xatmiJNI.tpsvcinfo_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return xatmiJNI.tpsvcinfo_flags_get(swigCPtr, this);
  }

  public void setCd(int value) {
    xatmiJNI.tpsvcinfo_cd_set(swigCPtr, this, value);
  }

  public int getCd() {
    return xatmiJNI.tpsvcinfo_cd_get(swigCPtr, this);
  }

  public tpsvcinfo() {
    this(xatmiJNI.new_tpsvcinfo(), true);
  }

}
