/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class tx implements txConstants {
  public static int tx_begin() {
    return txJNI.tx_begin();
  }

  public static int tx_close() {
    return txJNI.tx_close();
  }

  public static int tx_commit() {
    return txJNI.tx_commit();
  }

  public static int tx_open() {
    return txJNI.tx_open();
  }

  public static int tx_rollback() {
    return txJNI.tx_rollback();
  }

  public static int tx_set_commit_return(int arg0) {
    return txJNI.tx_set_commit_return(arg0);
  }

  public static int tx_set_transaction_control(int control) {
    return txJNI.tx_set_transaction_control(control);
  }

  public static int tx_set_transaction_timeout(int timeout) {
    return txJNI.tx_set_transaction_timeout(timeout);
  }

  public static int tx_info(tx_info_t arg0) {
    return txJNI.tx_info(tx_info_t.getCPtr(arg0), arg0);
  }

  public static int tx_suspend(SWIGTYPE_p_XID xid) {
    return txJNI.tx_suspend(SWIGTYPE_p_XID.getCPtr(xid));
  }

  public static int tx_resume(SWIGTYPE_p_XID xid) {
    return txJNI.tx_resume(SWIGTYPE_p_XID.getCPtr(xid));
  }

  public static int tx_get_commit_return() {
    return txJNI.tx_get_commit_return();
  }

}
