/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class tx_info_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tx_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tx_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        txJNI.delete_tx_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXid(SWIGTYPE_p_XID value) {
    txJNI.tx_info_t_xid_set(swigCPtr, this, SWIGTYPE_p_XID.getCPtr(value));
  }

  public SWIGTYPE_p_XID getXid() {
    return new SWIGTYPE_p_XID(txJNI.tx_info_t_xid_get(swigCPtr, this), true);
  }

  public void setWhen_return(int value) {
    txJNI.tx_info_t_when_return_set(swigCPtr, this, value);
  }

  public int getWhen_return() {
    return txJNI.tx_info_t_when_return_get(swigCPtr, this);
  }

  public void setTransaction_control(int value) {
    txJNI.tx_info_t_transaction_control_set(swigCPtr, this, value);
  }

  public int getTransaction_control() {
    return txJNI.tx_info_t_transaction_control_get(swigCPtr, this);
  }

  public void setTransaction_timeout(int value) {
    txJNI.tx_info_t_transaction_timeout_set(swigCPtr, this, value);
  }

  public int getTransaction_timeout() {
    return txJNI.tx_info_t_transaction_timeout_get(swigCPtr, this);
  }

  public void setTransaction_state(int value) {
    txJNI.tx_info_t_transaction_state_set(swigCPtr, this, value);
  }

  public int getTransaction_state() {
    return txJNI.tx_info_t_transaction_state_get(swigCPtr, this);
  }

  public tx_info_t() {
    this(txJNI.new_tx_info_t(), true);
  }

}
