/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface txConstants {
  public final static int TX_NOT_SUPPORTED = txJNI.TX_NOT_SUPPORTED_get();
  public final static int TX_OK = txJNI.TX_OK_get();
  public final static int TX_OUTSIDE = txJNI.TX_OUTSIDE_get();
  public final static int TX_ROLLBACK = txJNI.TX_ROLLBACK_get();
  public final static int TX_MIXED = txJNI.TX_MIXED_get();
  public final static int TX_HAZARD = txJNI.TX_HAZARD_get();
  public final static int TX_PROTOCOL_ERROR = txJNI.TX_PROTOCOL_ERROR_get();
  public final static int TX_ERROR = txJNI.TX_ERROR_get();
  public final static int TX_FAIL = txJNI.TX_FAIL_get();
  public final static int TX_EINVAL = txJNI.TX_EINVAL_get();
  public final static int TX_COMMITTED = txJNI.TX_COMMITTED_get();
  public final static int TX_NO_BEGIN = txJNI.TX_NO_BEGIN_get();
  public final static int TX_ROLLBACK_NO_BEGIN = txJNI.TX_ROLLBACK_NO_BEGIN_get();
  public final static int TX_MIXED_NO_BEGIN = txJNI.TX_MIXED_NO_BEGIN_get();
  public final static int TX_HAZARD_NO_BEGIN = txJNI.TX_HAZARD_NO_BEGIN_get();
  public final static int TX_COMMITTED_NO_BEGIN = txJNI.TX_COMMITTED_NO_BEGIN_get();
  public final static int TX_COMMIT_COMPLETED = txJNI.TX_COMMIT_COMPLETED_get();
  public final static int TX_COMMIT_DECISION_LOGGED = txJNI.TX_COMMIT_DECISION_LOGGED_get();
  public final static int TX_UNCHAINED = txJNI.TX_UNCHAINED_get();
  public final static int TX_CHAINED = txJNI.TX_CHAINED_get();
  public final static int TX_STACKED = txJNI.TX_STACKED_get();
  public final static int TX_ACTIVE = txJNI.TX_ACTIVE_get();
  public final static int TX_TIMEOUT_ROLLBACK_ONLY = txJNI.TX_TIMEOUT_ROLLBACK_ONLY_get();
  public final static int TX_ROLLBACK_ONLY = txJNI.TX_ROLLBACK_ONLY_get();
}
