/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class txJNI {
  public final static native int TX_NOT_SUPPORTED_get();
  public final static native int TX_OK_get();
  public final static native int TX_OUTSIDE_get();
  public final static native int TX_ROLLBACK_get();
  public final static native int TX_MIXED_get();
  public final static native int TX_HAZARD_get();
  public final static native int TX_PROTOCOL_ERROR_get();
  public final static native int TX_ERROR_get();
  public final static native int TX_FAIL_get();
  public final static native int TX_EINVAL_get();
  public final static native int TX_COMMITTED_get();
  public final static native int TX_NO_BEGIN_get();
  public final static native int TX_ROLLBACK_NO_BEGIN_get();
  public final static native int TX_MIXED_NO_BEGIN_get();
  public final static native int TX_HAZARD_NO_BEGIN_get();
  public final static native int TX_COMMITTED_NO_BEGIN_get();
  public final static native int TX_COMMIT_COMPLETED_get();
  public final static native int TX_COMMIT_DECISION_LOGGED_get();
  public final static native int TX_UNCHAINED_get();
  public final static native int TX_CHAINED_get();
  public final static native int TX_STACKED_get();
  public final static native int TX_ACTIVE_get();
  public final static native int TX_TIMEOUT_ROLLBACK_ONLY_get();
  public final static native int TX_ROLLBACK_ONLY_get();
  public final static native void tx_info_t_xid_set(long jarg1, tx_info_t jarg1_, long jarg2);
  public final static native long tx_info_t_xid_get(long jarg1, tx_info_t jarg1_);
  public final static native void tx_info_t_when_return_set(long jarg1, tx_info_t jarg1_, int jarg2);
  public final static native int tx_info_t_when_return_get(long jarg1, tx_info_t jarg1_);
  public final static native void tx_info_t_transaction_control_set(long jarg1, tx_info_t jarg1_, int jarg2);
  public final static native int tx_info_t_transaction_control_get(long jarg1, tx_info_t jarg1_);
  public final static native void tx_info_t_transaction_timeout_set(long jarg1, tx_info_t jarg1_, int jarg2);
  public final static native int tx_info_t_transaction_timeout_get(long jarg1, tx_info_t jarg1_);
  public final static native void tx_info_t_transaction_state_set(long jarg1, tx_info_t jarg1_, int jarg2);
  public final static native int tx_info_t_transaction_state_get(long jarg1, tx_info_t jarg1_);
  public final static native long new_tx_info_t();
  public final static native void delete_tx_info_t(long jarg1);
  public final static native int tx_begin();
  public final static native int tx_close();
  public final static native int tx_commit();
  public final static native int tx_open();
  public final static native int tx_rollback();
  public final static native int tx_set_commit_return(int jarg1);
  public final static native int tx_set_transaction_control(int jarg1);
  public final static native int tx_set_transaction_timeout(int jarg1);
  public final static native int tx_info(long jarg1, tx_info_t jarg1_);
  public final static native int tx_suspend(long jarg1);
  public final static native int tx_resume(long jarg1);
  public final static native int tx_get_commit_return();
}
