/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xa implements xaConstants {
  public static int ax_reg(int arg0, xid_t arg1, int arg2) {
    return xaJNI.ax_reg(arg0, xid_t.getCPtr(arg1), arg1, arg2);
  }

  public static int ax_unreg(int arg0, int arg1) {
    return xaJNI.ax_unreg(arg0, arg1);
  }

}
