/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xa_switch_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected xa_switch_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xa_switch_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xaJNI.delete_xa_switch_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    xaJNI.xa_switch_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return xaJNI.xa_switch_t_name_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    xaJNI.xa_switch_t_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return xaJNI.xa_switch_t_flags_get(swigCPtr, this);
  }

  public void setVersion(int value) {
    xaJNI.xa_switch_t_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return xaJNI.xa_switch_t_version_get(swigCPtr, this);
  }

  public void setXa_open_entry(SWIGTYPE_p_f_p_q_const__char_int_long__int value) {
    xaJNI.xa_switch_t_xa_open_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_int_long__int getXa_open_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_open_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_int_long__int(cPtr, false);
  }

  public void setXa_close_entry(SWIGTYPE_p_f_p_q_const__char_int_long__int value) {
    xaJNI.xa_switch_t_xa_close_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_int_long__int getXa_close_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_close_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_int_long__int(cPtr, false);
  }

  public void setXa_start_entry(SWIGTYPE_p_f_p_struct_xid_t_int_long__int value) {
    xaJNI.xa_switch_t_xa_start_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_xid_t_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_xid_t_int_long__int getXa_start_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_start_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_xid_t_int_long__int(cPtr, false);
  }

  public void setXa_end_entry(SWIGTYPE_p_f_p_struct_xid_t_int_long__int value) {
    xaJNI.xa_switch_t_xa_end_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_xid_t_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_xid_t_int_long__int getXa_end_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_end_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_xid_t_int_long__int(cPtr, false);
  }

  public void setXa_rollback_entry(SWIGTYPE_p_f_p_struct_xid_t_int_long__int value) {
    xaJNI.xa_switch_t_xa_rollback_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_xid_t_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_xid_t_int_long__int getXa_rollback_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_rollback_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_xid_t_int_long__int(cPtr, false);
  }

  public void setXa_prepare_entry(SWIGTYPE_p_f_p_struct_xid_t_int_long__int value) {
    xaJNI.xa_switch_t_xa_prepare_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_xid_t_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_xid_t_int_long__int getXa_prepare_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_prepare_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_xid_t_int_long__int(cPtr, false);
  }

  public void setXa_commit_entry(SWIGTYPE_p_f_p_struct_xid_t_int_long__int value) {
    xaJNI.xa_switch_t_xa_commit_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_xid_t_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_xid_t_int_long__int getXa_commit_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_commit_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_xid_t_int_long__int(cPtr, false);
  }

  public void setXa_recover_entry(SWIGTYPE_p_f_p_struct_xid_t_long_int_long__int value) {
    xaJNI.xa_switch_t_xa_recover_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_xid_t_long_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_xid_t_long_int_long__int getXa_recover_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_recover_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_xid_t_long_int_long__int(cPtr, false);
  }

  public void setXa_forget_entry(SWIGTYPE_p_f_p_struct_xid_t_int_long__int value) {
    xaJNI.xa_switch_t_xa_forget_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_xid_t_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_xid_t_int_long__int getXa_forget_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_forget_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_xid_t_int_long__int(cPtr, false);
  }

  public void setXa_complete_entry(SWIGTYPE_p_f_p_int_p_int_int_long__int value) {
    xaJNI.xa_switch_t_xa_complete_entry_set(swigCPtr, this, SWIGTYPE_p_f_p_int_p_int_int_long__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_int_p_int_int_long__int getXa_complete_entry() {
    long cPtr = xaJNI.xa_switch_t_xa_complete_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_int_p_int_int_long__int(cPtr, false);
  }

  public xa_switch_t() {
    this(xaJNI.new_xa_switch_t(), true);
  }

}
