/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface xaConstants {
  public final static int XIDDATASIZE = xaJNI.XIDDATASIZE_get();
  public final static int RMNAMESZ = xaJNI.RMNAMESZ_get();
  public final static int MAXINFOSIZE = xaJNI.MAXINFOSIZE_get();
  public final static int TMNOFLAGS = xaJNI.TMNOFLAGS_get();
  public final static int TMREGISTER = xaJNI.TMREGISTER_get();
  public final static int TMNOMIGRATE = xaJNI.TMNOMIGRATE_get();
  public final static int TMUSEASYNC = xaJNI.TMUSEASYNC_get();
  public final static int TMASYNC = xaJNI.TMASYNC_get();
  public final static int TMONEPHASE = xaJNI.TMONEPHASE_get();
  public final static int TMFAIL = xaJNI.TMFAIL_get();
  public final static int TMNOWAIT = xaJNI.TMNOWAIT_get();
  public final static int TMRESUME = xaJNI.TMRESUME_get();
  public final static int TMSUCCESS = xaJNI.TMSUCCESS_get();
  public final static int TMSUSPEND = xaJNI.TMSUSPEND_get();
  public final static int TMSTARTRSCAN = xaJNI.TMSTARTRSCAN_get();
  public final static int TMENDRSCAN = xaJNI.TMENDRSCAN_get();
  public final static int TMMULTIPLE = xaJNI.TMMULTIPLE_get();
  public final static int TMJOIN = xaJNI.TMJOIN_get();
  public final static int TMMIGRATE = xaJNI.TMMIGRATE_get();
  public final static int TM_JOIN = xaJNI.TM_JOIN_get();
  public final static int TM_RESUME = xaJNI.TM_RESUME_get();
  public final static int TM_OK = xaJNI.TM_OK_get();
  public final static int TMER_TMERR = xaJNI.TMER_TMERR_get();
  public final static int TMER_INVAL = xaJNI.TMER_INVAL_get();
  public final static int TMER_PROTO = xaJNI.TMER_PROTO_get();
  public final static int XA_RBBASE = xaJNI.XA_RBBASE_get();
  public final static int XA_RBROLLBACK = xaJNI.XA_RBROLLBACK_get();
  public final static int XA_RBCOMMFAIL = xaJNI.XA_RBCOMMFAIL_get();
  public final static int XA_RBDEADLOCK = xaJNI.XA_RBDEADLOCK_get();
  public final static int XA_RBINTEGRITY = xaJNI.XA_RBINTEGRITY_get();
  public final static int XA_RBOTHER = xaJNI.XA_RBOTHER_get();
  public final static int XA_RBPROTO = xaJNI.XA_RBPROTO_get();
  public final static int XA_RBTIMEOUT = xaJNI.XA_RBTIMEOUT_get();
  public final static int XA_RBTRANSIENT = xaJNI.XA_RBTRANSIENT_get();
  public final static int XA_RBEND = xaJNI.XA_RBEND_get();
  public final static int XA_NOMIGRATE = xaJNI.XA_NOMIGRATE_get();
  public final static int XA_HEURHAZ = xaJNI.XA_HEURHAZ_get();
  public final static int XA_HEURCOM = xaJNI.XA_HEURCOM_get();
  public final static int XA_HEURRB = xaJNI.XA_HEURRB_get();
  public final static int XA_HEURMIX = xaJNI.XA_HEURMIX_get();
  public final static int XA_RETRY = xaJNI.XA_RETRY_get();
  public final static int XA_RDONLY = xaJNI.XA_RDONLY_get();
  public final static int XA_OK = xaJNI.XA_OK_get();
  public final static int XAER_ASYNC = xaJNI.XAER_ASYNC_get();
  public final static int XAER_RMERR = xaJNI.XAER_RMERR_get();
  public final static int XAER_NOTA = xaJNI.XAER_NOTA_get();
  public final static int XAER_INVAL = xaJNI.XAER_INVAL_get();
  public final static int XAER_PROTO = xaJNI.XAER_PROTO_get();
  public final static int XAER_RMFAIL = xaJNI.XAER_RMFAIL_get();
  public final static int XAER_DUPID = xaJNI.XAER_DUPID_get();
  public final static int XAER_OUTSIDE = xaJNI.XAER_OUTSIDE_get();
}
