/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xaJNI {
  public final static native int XIDDATASIZE_get();
  public final static native void xid_t_formatID_set(long jarg1, xid_t jarg1_, int jarg2);
  public final static native int xid_t_formatID_get(long jarg1, xid_t jarg1_);
  public final static native void xid_t_gtrid_length_set(long jarg1, xid_t jarg1_, int jarg2);
  public final static native int xid_t_gtrid_length_get(long jarg1, xid_t jarg1_);
  public final static native void xid_t_bqual_length_set(long jarg1, xid_t jarg1_, int jarg2);
  public final static native int xid_t_bqual_length_get(long jarg1, xid_t jarg1_);
  public final static native void xid_t_data_set(long jarg1, xid_t jarg1_, String jarg2);
  public final static native String xid_t_data_get(long jarg1, xid_t jarg1_);
  public final static native long new_xid_t();
  public final static native void delete_xid_t(long jarg1);
  public final static native int ax_reg(int jarg1, long jarg2, xid_t jarg2_, int jarg3);
  public final static native int ax_unreg(int jarg1, int jarg2);
  public final static native int RMNAMESZ_get();
  public final static native void xa_switch_t_name_set(long jarg1, xa_switch_t jarg1_, String jarg2);
  public final static native String xa_switch_t_name_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_flags_set(long jarg1, xa_switch_t jarg1_, int jarg2);
  public final static native int xa_switch_t_flags_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_version_set(long jarg1, xa_switch_t jarg1_, int jarg2);
  public final static native int xa_switch_t_version_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_open_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_open_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_close_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_close_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_start_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_start_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_end_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_end_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_rollback_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_rollback_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_prepare_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_prepare_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_commit_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_commit_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_recover_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_recover_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_forget_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_forget_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native void xa_switch_t_xa_complete_entry_set(long jarg1, xa_switch_t jarg1_, long jarg2);
  public final static native long xa_switch_t_xa_complete_entry_get(long jarg1, xa_switch_t jarg1_);
  public final static native long new_xa_switch_t();
  public final static native void delete_xa_switch_t(long jarg1);
  public final static native int MAXINFOSIZE_get();
  public final static native int TMNOFLAGS_get();
  public final static native int TMREGISTER_get();
  public final static native int TMNOMIGRATE_get();
  public final static native int TMUSEASYNC_get();
  public final static native int TMASYNC_get();
  public final static native int TMONEPHASE_get();
  public final static native int TMFAIL_get();
  public final static native int TMNOWAIT_get();
  public final static native int TMRESUME_get();
  public final static native int TMSUCCESS_get();
  public final static native int TMSUSPEND_get();
  public final static native int TMSTARTRSCAN_get();
  public final static native int TMENDRSCAN_get();
  public final static native int TMMULTIPLE_get();
  public final static native int TMJOIN_get();
  public final static native int TMMIGRATE_get();
  public final static native int TM_JOIN_get();
  public final static native int TM_RESUME_get();
  public final static native int TM_OK_get();
  public final static native int TMER_TMERR_get();
  public final static native int TMER_INVAL_get();
  public final static native int TMER_PROTO_get();
  public final static native int XA_RBBASE_get();
  public final static native int XA_RBROLLBACK_get();
  public final static native int XA_RBCOMMFAIL_get();
  public final static native int XA_RBDEADLOCK_get();
  public final static native int XA_RBINTEGRITY_get();
  public final static native int XA_RBOTHER_get();
  public final static native int XA_RBPROTO_get();
  public final static native int XA_RBTIMEOUT_get();
  public final static native int XA_RBTRANSIENT_get();
  public final static native int XA_RBEND_get();
  public final static native int XA_NOMIGRATE_get();
  public final static native int XA_HEURHAZ_get();
  public final static native int XA_HEURCOM_get();
  public final static native int XA_HEURRB_get();
  public final static native int XA_HEURMIX_get();
  public final static native int XA_RETRY_get();
  public final static native int XA_RDONLY_get();
  public final static native int XA_OK_get();
  public final static native int XAER_ASYNC_get();
  public final static native int XAER_RMERR_get();
  public final static native int XAER_NOTA_get();
  public final static native int XAER_INVAL_get();
  public final static native int XAER_PROTO_get();
  public final static native int XAER_RMFAIL_get();
  public final static native int XAER_DUPID_get();
  public final static native int XAER_OUTSIDE_get();
}
