/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xatmi implements xatmiConstants {
  public static String tpalloc(String type, String subtype, int size) {
    return xatmiJNI.tpalloc(type, subtype, size);
  }

  public static String tprealloc(String ptr, int size) {
    return xatmiJNI.tprealloc(ptr, size);
  }

  public static int tpcall(String svc, String idata, int ilen, SWIGTYPE_p_p_char odata, SWIGTYPE_p_long olen, int flags) {
    return xatmiJNI.tpcall(svc, idata, ilen, SWIGTYPE_p_p_char.getCPtr(odata), SWIGTYPE_p_long.getCPtr(olen), flags);
  }

  public static int tpacall(String svc, String idata, int ilen, int flags) {
    return xatmiJNI.tpacall(svc, idata, ilen, flags);
  }

  public static int tpgetrply(SWIGTYPE_p_int idPtr, SWIGTYPE_p_p_char odata, SWIGTYPE_p_long olen, int flags) {
    return xatmiJNI.tpgetrply(SWIGTYPE_p_int.getCPtr(idPtr), SWIGTYPE_p_p_char.getCPtr(odata), SWIGTYPE_p_long.getCPtr(olen), flags);
  }

  public static int tpcancel(int id) {
    return xatmiJNI.tpcancel(id);
  }

  public static int tptypes(String buffer, String type, String subtype) {
    return xatmiJNI.tptypes(buffer, type, subtype);
  }

  public static void tpfree(String ptr) {
    xatmiJNI.tpfree(ptr);
  }

  public static void tpreturn(int rval, int rcode, String data, int len, int flags) {
    xatmiJNI.tpreturn(rval, rcode, data, len, flags);
  }

  public static int tpadvertise(String svcname, SWIGTYPE_p_f_p_struct_tpsvcinfo__void func) {
    return xatmiJNI.tpadvertise(svcname, SWIGTYPE_p_f_p_struct_tpsvcinfo__void.getCPtr(func));
  }

  public static int tpunadvertise(String svcname) {
    return xatmiJNI.tpunadvertise(svcname);
  }

  public static int tpsend(int id, String idata, int ilen, int flags, SWIGTYPE_p_long revent) {
    return xatmiJNI.tpsend(id, idata, ilen, flags, SWIGTYPE_p_long.getCPtr(revent));
  }

  public static int tprecv(int id, SWIGTYPE_p_p_char odata, SWIGTYPE_p_long olen, int flags, SWIGTYPE_p_long event) {
    return xatmiJNI.tprecv(id, SWIGTYPE_p_p_char.getCPtr(odata), SWIGTYPE_p_long.getCPtr(olen), flags, SWIGTYPE_p_long.getCPtr(event));
  }

  public static int tpconnect(String svc, String idata, int ilen, int flags) {
    return xatmiJNI.tpconnect(svc, idata, ilen, flags);
  }

  public static int tpdiscon(int id) {
    return xatmiJNI.tpdiscon(id);
  }

  public static int casual_get_tperrno() {
    return xatmiJNI.casual_get_tperrno();
  }

  public static int casual_get_tpurcode() {
    return xatmiJNI.casual_get_tpurcode();
  }

  public static String tperrnostring(int error) {
    return xatmiJNI.tperrnostring(error);
  }

  public static int tpsvrinit(int argc, SWIGTYPE_p_p_char argv) {
    return xatmiJNI.tpsvrinit(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static void tpsvrdone() {
    xatmiJNI.tpsvrdone();
  }

  public static void casual_service_forward(String service, String data, int size) {
    xatmiJNI.casual_service_forward(service, data, size);
  }

}
