/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xatmiJNI {
  public final static native int TPNOBLOCK_get();
  public final static native int TPSIGRSTRT_get();
  public final static native int TPNOREPLY_get();
  public final static native int TPNOTRAN_get();
  public final static native int TPTRAN_get();
  public final static native int TPNOTIME_get();
  public final static native int TPGETANY_get();
  public final static native int TPNOCHANGE_get();
  public final static native int TPCONV_get();
  public final static native int TPSENDONLY_get();
  public final static native int TPRECVONLY_get();
  public final static native int TPFAIL_get();
  public final static native int TPSUCCESS_get();
  public final static native int XATMI_SERVICE_NAME_LENGTH_get();
  public final static native void tpsvcinfo_name_set(long jarg1, tpsvcinfo jarg1_, String jarg2);
  public final static native String tpsvcinfo_name_get(long jarg1, tpsvcinfo jarg1_);
  public final static native void tpsvcinfo_data_set(long jarg1, tpsvcinfo jarg1_, String jarg2);
  public final static native String tpsvcinfo_data_get(long jarg1, tpsvcinfo jarg1_);
  public final static native void tpsvcinfo_len_set(long jarg1, tpsvcinfo jarg1_, int jarg2);
  public final static native int tpsvcinfo_len_get(long jarg1, tpsvcinfo jarg1_);
  public final static native void tpsvcinfo_flags_set(long jarg1, tpsvcinfo jarg1_, int jarg2);
  public final static native int tpsvcinfo_flags_get(long jarg1, tpsvcinfo jarg1_);
  public final static native void tpsvcinfo_cd_set(long jarg1, tpsvcinfo jarg1_, int jarg2);
  public final static native int tpsvcinfo_cd_get(long jarg1, tpsvcinfo jarg1_);
  public final static native long new_tpsvcinfo();
  public final static native void delete_tpsvcinfo(long jarg1);
  public final static native String X_OCTET_get();
  public final static native String X_C_TYPE_get();
  public final static native String X_COMMON_get();
  public final static native int TPEBADDESC_get();
  public final static native int TPEBLOCK_get();
  public final static native int TPEINVAL_get();
  public final static native int TPELIMIT_get();
  public final static native int TPENOENT_get();
  public final static native int TPEOS_get();
  public final static native int TPEPROTO_get();
  public final static native int TPESVCERR_get();
  public final static native int TPESVCFAIL_get();
  public final static native int TPESYSTEM_get();
  public final static native int TPETIME_get();
  public final static native int TPETRAN_get();
  public final static native int TPGOTSIG_get();
  public final static native int TPEITYPE_get();
  public final static native int TPEOTYPE_get();
  public final static native int TPEEVENT_get();
  public final static native int TPEMATCH_get();
  public final static native int TPEV_DISCONIMM_get();
  public final static native int TPEV_SVCERR_get();
  public final static native int TPEV_SVCFAIL_get();
  public final static native int TPEV_SVCSUCC_get();
  public final static native int TPEV_SENDONLY_get();
  public final static native String tpalloc(String jarg1, String jarg2, int jarg3);
  public final static native String tprealloc(String jarg1, int jarg2);
  public final static native int tpcall(String jarg1, String jarg2, int jarg3, long jarg4, long jarg5, int jarg6);
  public final static native int tpacall(String jarg1, String jarg2, int jarg3, int jarg4);
  public final static native int tpgetrply(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native int tpcancel(int jarg1);
  public final static native int tptypes(String jarg1, String jarg2, String jarg3);
  public final static native void tpfree(String jarg1);
  public final static native void tpreturn(int jarg1, int jarg2, String jarg3, int jarg4, int jarg5);
  public final static native int tpadvertise(String jarg1, long jarg2);
  public final static native int tpunadvertise(String jarg1);
  public final static native int tpsend(int jarg1, String jarg2, int jarg3, int jarg4, long jarg5);
  public final static native int tprecv(int jarg1, long jarg2, long jarg3, int jarg4, long jarg5);
  public final static native int tpconnect(String jarg1, String jarg2, int jarg3, int jarg4);
  public final static native int tpdiscon(int jarg1);
  public final static native int casual_get_tperrno();
  public final static native int casual_get_tpurcode();
  public final static native String CASUAL_BUFFER_BINARY_TYPE_get();
  public final static native int CASUAL_BUFFER_BINARY_SUBTYPE_get();
  public final static native String CASUAL_BUFFER_JSON_TYPE_get();
  public final static native int CASUAL_BUFFER_JSON_SUBTYPE_get();
  public final static native String CASUAL_BUFFER_YAML_TYPE_get();
  public final static native int CASUAL_BUFFER_YAML_SUBTYPE_get();
  public final static native String CASUAL_BUFFER_XML_TYPE_get();
  public final static native int CASUAL_BUFFER_XML_SUBTYPE_get();
  public final static native String tperrnostring(int jarg1);
  public final static native int tpsvrinit(int jarg1, long jarg2);
  public final static native void tpsvrdone();
  public final static native void casual_service_forward(String jarg1, String jarg2, int jarg3);
}
