/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface xatmiConstants {
  public final static int TPNOBLOCK = xatmiJNI.TPNOBLOCK_get();
  public final static int TPSIGRSTRT = xatmiJNI.TPSIGRSTRT_get();
  public final static int TPNOREPLY = xatmiJNI.TPNOREPLY_get();
  public final static int TPNOTRAN = xatmiJNI.TPNOTRAN_get();
  public final static int TPTRAN = xatmiJNI.TPTRAN_get();
  public final static int TPNOTIME = xatmiJNI.TPNOTIME_get();
  public final static int TPGETANY = xatmiJNI.TPGETANY_get();
  public final static int TPNOCHANGE = xatmiJNI.TPNOCHANGE_get();
  public final static int TPCONV = xatmiJNI.TPCONV_get();
  public final static int TPSENDONLY = xatmiJNI.TPSENDONLY_get();
  public final static int TPRECVONLY = xatmiJNI.TPRECVONLY_get();
  public final static int TPFAIL = xatmiJNI.TPFAIL_get();
  public final static int TPSUCCESS = xatmiJNI.TPSUCCESS_get();
  public final static int XATMI_SERVICE_NAME_LENGTH = xatmiJNI.XATMI_SERVICE_NAME_LENGTH_get();
  public final static String X_OCTET = xatmiJNI.X_OCTET_get();
  public final static String X_C_TYPE = xatmiJNI.X_C_TYPE_get();
  public final static String X_COMMON = xatmiJNI.X_COMMON_get();
  public final static int TPEBADDESC = xatmiJNI.TPEBADDESC_get();
  public final static int TPEBLOCK = xatmiJNI.TPEBLOCK_get();
  public final static int TPEINVAL = xatmiJNI.TPEINVAL_get();
  public final static int TPELIMIT = xatmiJNI.TPELIMIT_get();
  public final static int TPENOENT = xatmiJNI.TPENOENT_get();
  public final static int TPEOS = xatmiJNI.TPEOS_get();
  public final static int TPEPROTO = xatmiJNI.TPEPROTO_get();
  public final static int TPESVCERR = xatmiJNI.TPESVCERR_get();
  public final static int TPESVCFAIL = xatmiJNI.TPESVCFAIL_get();
  public final static int TPESYSTEM = xatmiJNI.TPESYSTEM_get();
  public final static int TPETIME = xatmiJNI.TPETIME_get();
  public final static int TPETRAN = xatmiJNI.TPETRAN_get();
  public final static int TPGOTSIG = xatmiJNI.TPGOTSIG_get();
  public final static int TPEITYPE = xatmiJNI.TPEITYPE_get();
  public final static int TPEOTYPE = xatmiJNI.TPEOTYPE_get();
  public final static int TPEEVENT = xatmiJNI.TPEEVENT_get();
  public final static int TPEMATCH = xatmiJNI.TPEMATCH_get();
  public final static int TPEV_DISCONIMM = xatmiJNI.TPEV_DISCONIMM_get();
  public final static int TPEV_SVCERR = xatmiJNI.TPEV_SVCERR_get();
  public final static int TPEV_SVCFAIL = xatmiJNI.TPEV_SVCFAIL_get();
  public final static int TPEV_SVCSUCC = xatmiJNI.TPEV_SVCSUCC_get();
  public final static int TPEV_SENDONLY = xatmiJNI.TPEV_SENDONLY_get();
  public final static String CASUAL_BUFFER_BINARY_TYPE = xatmiJNI.CASUAL_BUFFER_BINARY_TYPE_get();
  public final static int CASUAL_BUFFER_BINARY_SUBTYPE = xatmiJNI.CASUAL_BUFFER_BINARY_SUBTYPE_get();
  public final static String CASUAL_BUFFER_JSON_TYPE = xatmiJNI.CASUAL_BUFFER_JSON_TYPE_get();
  public final static int CASUAL_BUFFER_JSON_SUBTYPE = xatmiJNI.CASUAL_BUFFER_JSON_SUBTYPE_get();
  public final static String CASUAL_BUFFER_YAML_TYPE = xatmiJNI.CASUAL_BUFFER_YAML_TYPE_get();
  public final static int CASUAL_BUFFER_YAML_SUBTYPE = xatmiJNI.CASUAL_BUFFER_YAML_SUBTYPE_get();
  public final static String CASUAL_BUFFER_XML_TYPE = xatmiJNI.CASUAL_BUFFER_XML_TYPE_get();
  public final static int CASUAL_BUFFER_XML_SUBTYPE = xatmiJNI.CASUAL_BUFFER_XML_SUBTYPE_get();
}
