/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xid_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected xid_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xid_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xaJNI.delete_xid_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFormatID(int value) {
    xaJNI.xid_t_formatID_set(swigCPtr, this, value);
  }

  public int getFormatID() {
    return xaJNI.xid_t_formatID_get(swigCPtr, this);
  }

  public void setGtrid_length(int value) {
    xaJNI.xid_t_gtrid_length_set(swigCPtr, this, value);
  }

  public int getGtrid_length() {
    return xaJNI.xid_t_gtrid_length_get(swigCPtr, this);
  }

  public void setBqual_length(int value) {
    xaJNI.xid_t_bqual_length_set(swigCPtr, this, value);
  }

  public int getBqual_length() {
    return xaJNI.xid_t_bqual_length_get(swigCPtr, this);
  }

  public void setData(String value) {
    xaJNI.xid_t_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return xaJNI.xid_t_data_get(swigCPtr, this);
  }

  public xid_t() {
    this(xaJNI.new_xid_t(), true);
  }

}
