from casual.middleware.make.dsl import *

IncludePaths( ['server/include',
    'common/source',
    '../../xatmi/include',
    '$(CASUAL_OPTIONAL_INCLUDE_PATHS)',
    ])
    
LibraryPaths( [ 'server/bin',
    '../../xatmi/bin',
    '../../common/bin',
    '../../queue/bin',
    '../../buffer/bin',
    '../../configuration/bin',
    '../../serviceframework/bin',
    '$(CASUAL_OPTIONAL_LIBRARY_PATHS)',
    ])



install_bin = []


target = LinkServer( 'server/bin/simple-chat-protobuffer',
    [ Compile( 'server/source/server.cpp')],
    [ Compile( 'common/source/chat.pb.cpp')],
    [ 
        'casual-xatmi', 
    ],
    'server/source/simple-chat-protobuffer.services.yaml')

install_bin.append( target)




#
# Install
#
Install( install_bin,'$(CASUAL_HOME)/simple-chat-protobuffer/bin')


# domain examples
#Install( [ 'domain/domain.md'],'$(CASUAL_HOME)/simple-chat-protobuffer/domain')


# single domain minimal example
#Install( [ 'domain/single/minimal/minimal.md', 'domain/single/minimal/domain.env'],'$(CASUAL_HOME)/example/domain/single/minimal')
#Install( [ 'domain/single/minimal/configuration/domain.yaml'],'$(CASUAL_HOME)/example/domain/single/minimal/configuration')

# multi domian minimal example
#Install( [ 'domain/multiple/minimal/minimal.md'],'$(CASUAL_HOME)/example/domain/multiple/minimal')

#Install( [ 'domain/multiple/minimal/domain1/domain.env'],'$(CASUAL_HOME)/example/domain/multiple/minimal/domain1')
#Install( [ 'domain/multiple/minimal/domain1/configuration/domain.yaml'],'$(CASUAL_HOME)/example/domain/multiple/minimal/domain1/configuration')

#Install( [ 'domain/multiple/minimal/domain2/domain.env'],'$(CASUAL_HOME)/example/domain/multiple/minimal/domain2')
#Install( [ 'domain/multiple/minimal/domain2/configuration/domain.yaml'],'$(CASUAL_HOME)/example/domain/multiple/minimal/domain2/configuration')








